# 1. Input
input {
  file {
    # 도커 컨테이너 안에서 바라보는 우리 로그 파일의 위치
    path => "/usr/share/logstash/logs/waiting-api-log.log"

    # 처음 켤 때 파일의 맨 처음부터 끝까지 싹 다 읽어오라는 뜻
    start_position => "beginning"

    # 파일이 끝났는지 확인하는 주기 (기본 1초에 한 번씩 감시)
    stat_interval => 1
  }
}

# 2. Filter
filter {
  # 이번 기초 실습에서는 로그 텍스트를 있는 그대로 보낼 거라 비워두기!
  # (나중에 실력이 쌓이면 여기서 에러 메시지만 따로 자르거나 가공 가능)
  date {
      match => ["log_time", "yyyy-MM-dd'T'HH:mm:ss.SSSZ"]
      target => "@timestamp"
      timezone => "Asia/Seoul"
  }
}

# 3. Output
output {
  # 우리의 목적지인 엘라스틱서치로 보냄
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    # 엘라스틱서치에 저장될 인덱스 이름! 날짜별로 분류함
    index => "waiting-api-logs-%{+YYYY.MM.dd}"
  }

  # 잘 전송되고 있는지 도커 콘솔 화면에서도 확인하기 위해 추가
  stdout { codec => rubydebug }
}
